apiVersion: apps/v1
kind: Deployment   # 👈 ye change kar
metadata:
  name: mehar-deploy
  labels:
    app: meharpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meharpod
  template:
    metadata:
      labels:
        app: meharpod
    spec:
      containers:
      - name: meharcon
        image: nginx
        ports:
        - containerPort: 80
